export const LAYERS = {
  carrier: { label: "Carriers & public phone network", color: "#d66843", short: "PHONE" },
  signal: { label: "Call setup messages", color: "#e0a526", short: "SETUP" },
  media: { label: "Live audio path", color: "#1d8f86", short: "AUDIO" },
  control: { label: "SaaS control plane", color: "#5b67a5", short: "APP" },
  safety: { label: "Safety & operations", color: "#b24c68", short: "OPS" },
};

export const TERMS = {
  SaaS: { expansion: "Software as a service", plain: "One hosted product that serves many customer organizations through the internet." },
  "E.164": { expansion: "ITU international telephone-numbering standard", plain: "The standard for globally unique phone numbers of up to 15 digits, starting with a country code. Apps commonly write one with a leading +, such as +1 520 555 0142." },
  DID: { expansion: "Direct Inward Dialing number", plain: "A public phone number a carrier routes into your service. It is an address, not a physical line or capacity limit." },
  PSTN: { expansion: "Public Switched Telephone Network", plain: "The interconnected carrier networks that let ordinary phone numbers call one another." },
  IP: { expansion: "Internet Protocol", plain: "The addressing and packet-delivery system used to move data between networked devices." },
  SIP: { expansion: "Session Initiation Protocol", plain: "The call-control messages used to start, change, and end a phone session. SIP does not carry the voice audio." },
  INVITE: { expansion: "SIP request to start a session", plain: "The message that asks another phone system or endpoint to begin a call." },
  ACK: { expansion: "SIP acknowledgement", plain: "The message confirming that the final answer to an INVITE was received." },
  BYE: { expansion: "SIP request to end a session", plain: "The message sent by either side to hang up an established call." },
  REGISTER: { expansion: "SIP endpoint registration request", plain: "A phone uses this to announce where it can currently receive calls. Many carrier trunks do not use registration." },
  "SIP responses": { expansion: "Three-digit call-setup results", plain: "100 means processing, 180 means ringing, 200 means accepted, 4xx means a request or destination problem, and 5xx means a server or provider problem." },
  "503": { expansion: "Service Unavailable", plain: "A temporary failure saying the carrier or peer cannot currently handle the call." },
  SDP: { expansion: "Session Description Protocol", plain: "A description carried inside call setup messages that says where audio should go and which audio formats each side supports." },
  codec: { expansion: "Coder-decoder", plain: "The format and algorithm used to turn sound into digital packets and back. Choosing a shared codec is different from converting between codecs." },
  PCMU: { expansion: "Pulse Code Modulation, µ-law", plain: "A common North American telephone-audio codec, also called G.711 µ-law." },
  sendrecv: { expansion: "Send and receive", plain: "An SDP direction saying this endpoint intends to both transmit and receive media." },
  SBC: { expansion: "Session Border Controller", plain: "The guarded entrance to your calling platform. It checks, limits, and normalizes call traffic from outside networks." },
  PBX: { expansion: "Private Branch Exchange", plain: "A business phone system that connects internal extensions and outside calls. An SBC protects the edge; it is not the PBX." },
  ACL: { expansion: "Access Control List", plain: "A rule list saying which network peers or addresses are allowed or denied." },
  NAT: { expansion: "Network Address Translation", plain: "A router technique that lets private devices share public addresses; it can make audio paths harder to reach." },
  TLS: { expansion: "Transport Layer Security", plain: "Encryption for one network connection. With SIP it can protect signaling, but it does not automatically encrypt the audio." },
  RTP: { expansion: "Real-time Transport Protocol", plain: "The stream of time-sensitive packets that usually carries the actual voice audio." },
  RTCP: { expansion: "RTP Control Protocol", plain: "Companion reports about an RTP stream, including packet loss, timing, and jitter." },
  SRTP: { expansion: "Secure Real-time Transport Protocol", plain: "The encrypted and integrity-protected form of RTP audio." },
  UDP: { expansion: "User Datagram Protocol", plain: "A low-overhead packet transport commonly used for live audio because it does not wait to resend late packets." },
  RTT: { expansion: "Round-trip time", plain: "How long a packet takes to travel to the other side and back; one indicator of conversational delay." },
  MOS: { expansion: "Mean Opinion Score", plain: "A model-based estimate of perceived call quality. It is not a person directly rating this call." },
  PDD: { expansion: "Post-dial delay", plain: "The time from finishing the dial to hearing ringing or another useful response." },
  ASR: { expansion: "Answer-seizure ratio", plain: "The share of call attempts that reach an answered state; useful for comparing routes, but affected by caller behavior too." },
  IVR: { expansion: "Interactive Voice Response", plain: "The automated call menu that plays prompts and gathers keypad or spoken input." },
  DTMF: { expansion: "Dual-tone multi-frequency", plain: "Telephone keypad input. It may be sent as special network events rather than audible tones." },
  RFC: { expansion: "Request for Comments", plain: "A numbered technical specification published through the Internet Engineering Task Force process." },
  WebRTC: { expansion: "Web Real-Time Communication", plain: "Browser technology for microphone access and secure, real-time audio or video connections." },
  HTTPS: { expansion: "Hypertext Transfer Protocol Secure", plain: "The encrypted website or application connection used for browser controls and app signaling; it is separate from the live audio path." },
  ICE: { expansion: "Interactive Connectivity Establishment", plain: "The WebRTC process that tests possible network paths and chooses one that works." },
  STUN: { expansion: "Session Traversal Utilities for NAT", plain: "A service that helps an endpoint discover its public-facing network address. It does not relay the call." },
  TURN: { expansion: "Traversal Using Relays around NAT", plain: "A relay used when WebRTC endpoints cannot establish a usable direct path." },
  "DTLS-SRTP": { expansion: "Datagram TLS keying for Secure RTP", plain: "The WebRTC mechanism that negotiates keys and protects the live media stream." },
  FIFO: { expansion: "First in, first out", plain: "A simple queue where the earliest arrival is handled first." },
  SLA: { expansion: "Service-level agreement or target", plain: "A measurable promise or goal, such as answering a percentage of calls within a set time." },
  CRM: { expansion: "Customer relationship management", plain: "The customer-record system an agent may use alongside the phone service." },
  CPU: { expansion: "Central processing unit", plain: "The compute resource that performs software work, including expensive audio conversion." },
  UUID: { expansion: "Universally unique identifier", plain: "A long identifier used to distinguish a particular call leg or event without collisions." },
  CDR: { expansion: "Call Detail Record", plain: "A technical record for one call leg. Several CDRs can belong to one customer conversation." },
  "A-leg / B-leg": { expansion: "Incoming side / destination side", plain: "Separate channel segments of one interaction: usually the caller side and one or more agent or destination sides." },
  "PCI DSS": { expansion: "Payment Card Industry Data Security Standard", plain: "Security requirements that apply when systems store, process, or transmit payment-card data." },
  HIPAA: { expansion: "Health Insurance Portability and Accountability Act", plain: "A US law whose privacy and security rules can apply when the service handles protected health information." },
  "STIR/SHAKEN": { expansion: "Secure Telephone Identity Revisited / Signature-based Handling of Asserted information using toKENs", plain: "A provider-signed caller-ID attestation framework. It does not prove who the speaking person is." },
  TCPA: { expansion: "Telephone Consumer Protection Act", plain: "A US law governing certain automated calls, texts, consent, and related practices." },
  TSR: { expansion: "Telemarketing Sales Rule", plain: "A US federal rule covering telemarketing practices such as do-not-call obligations and abandoned calls." },
  HTTP: { expansion: "Hypertext Transfer Protocol", plain: "The request-and-response protocol used by websites and APIs. A healthy HTTP endpoint does not prove that phone audio works." },
  IETF: { expansion: "Internet Engineering Task Force", plain: "The standards community that publishes the RFC specifications used by SIP, RTP, and many internet protocols." },
  W3C: { expansion: "World Wide Web Consortium", plain: "The standards organization that publishes the WebRTC browser specification." },
  NANPA: { expansion: "North American Numbering Plan Administrator", plain: "The administrator responsible for numbering resources across the North American Numbering Plan." },
  eCFR: { expansion: "Electronic Code of Federal Regulations", plain: "The official online presentation of current US federal regulations." },
  FCC: { expansion: "Federal Communications Commission", plain: "The US federal agency that regulates interstate and international communications." },
  FTC: { expansion: "Federal Trade Commission", plain: "The US federal agency whose rules include telemarketing consumer protections." },
  "PCI SSC": { expansion: "Payment Card Industry Security Standards Council", plain: "The body that maintains PCI data-security standards and guidance." },
  HHS: { expansion: "US Department of Health and Human Services", plain: "The federal department that publishes HIPAA guidance." },
};

export const SOURCES = [
  { id: "rfc3261", title: "SIP: Session Initiation Protocol", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc3261" },
  { id: "rfc3264", title: "SDP Offer/Answer Model", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc3264" },
  { id: "rfc3550", title: "RTP and RTCP", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc3550" },
  { id: "rfc3711", title: "Secure RTP", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc3711" },
  { id: "rfc4733", title: "RTP Telephone Events", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc4733" },
  { id: "rfc8445", title: "Interactive Connectivity Establishment", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc8445" },
  { id: "rfc8489", title: "Session Traversal Utilities for NAT", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc8489" },
  { id: "rfc8656", title: "Traversal Using Relays around NAT", org: "IETF", url: "https://datatracker.ietf.org/doc/html/rfc8656" },
  { id: "webrtc", title: "WebRTC Recommendation", org: "W3C", url: "https://www.w3.org/TR/webrtc/" },
  { id: "fs-core", title: "FreeSWITCH Foundations", org: "SignalWire", url: "https://developer.signalwire.com/freeswitch/foundations/introduction/" },
  { id: "fs-queues", title: "FreeSWITCH Call Queues", org: "SignalWire", url: "https://developer.signalwire.com/freeswitch/applications/call-queues/" },
  { id: "fs-cdr", title: "FreeSWITCH CDRs", org: "SignalWire", url: "https://developer.signalwire.com/freeswitch/integration/cdr/" },
  { id: "nanpa", title: "North American Numbering Plan", org: "NANPA", url: "https://www.nanpa.com/about" },
  { id: "fcc911", title: "Emergency Calling Rules", org: "eCFR", url: "https://www.ecfr.gov/current/title-47/chapter-I/subchapter-A/part-9" },
  { id: "fccstir", title: "STIR/SHAKEN Framework", org: "FCC", url: "https://docs.fcc.gov/public/attachments/FCC-20-42A1.pdf" },
  { id: "ftc", title: "Telemarketing Sales Rule", org: "FTC", url: "https://www.ftc.gov/business-guidance/resources/complying-telemarketing-sales-rule" },
  { id: "pci", title: "Protecting Telephone-Based Payment Card Data", org: "PCI SSC", url: "https://www.pcisecuritystandards.org/documents/Protecting_Telephone_Based_Payment_Card_Data_v3-0_nov_2018.pdf" },
  { id: "hhs", title: "HIPAA Cloud Computing Guidance", org: "HHS", url: "https://www.hhs.gov/hipaa/for-professionals/special-topics/health-information-technology/cloud-computing/index.html" },
];

export const STATIONS = [
  {
    id: "number-yard", number: 1, name: "Number Yard", kicker: "Give the customer an address", layer: "carrier",
    terms: ["DID", "E.164"],
    x: -8.2, z: 4.9, kind: "tower", metric: "Inventory state", failure: "Number is not mapped to a tenant",
    summary: "A Direct Inward Dialing (DID) number is a routable telephone address—not a physical line, login, or promise of call capacity.",
    lesson: "Your carrier assigns or ports a number written in the international E.164 format and routes calls for it toward your service. Keep number inventory, tenant ownership, routing state, and concurrent-call capacity as separate records.",
    build: "Create a tenant, reserve a number, verify its regulatory address where required, and make one authoritative tenant + DID mapping.",
    signal: "No call-setup conversation exists yet.", media: "No live audio exists yet.", state: "customer account 17 owns +1 520 555 0142",
    sources: ["nanpa"]
  },
  {
    id: "pstn", number: 2, name: "Public Phone Network", kicker: "The Public Switched Telephone Network (PSTN)", layer: "carrier",
    terms: ["PSTN", "IP"],
    x: -5.6, z: 4.9, kind: "exchange", metric: "Route completion", failure: "Unreachable or misrouted number",
    summary: "The Public Switched Telephone Network (PSTN) finds the provider responsible for the dialed number; it is not simply “the Internet for phones.”",
    lesson: "A caller's access network and upstream carriers perform numbering and interconnection work before your software sees a call. Much transport is IP, but carriers still own regulated numbering and routing boundaries.",
    build: "Choose origination and termination carriers with coverage, emergency services, porting support, and redundant interconnects.",
    signal: "Carrier call-setup messages are translated toward your service.", media: "Audio has not reached your edge.", state: "dialed number = +1 520 555 0142",
    sources: ["nanpa"]
  },
  {
    id: "carrier", number: 3, name: "Carrier Dock", kicker: "Interconnect the public network", layer: "carrier",
    terms: ["SIP", "SDP", "INVITE", "codec", "PDD", "ASR", "503"],
    x: -2.8, z: 4.9, kind: "warehouse", metric: "PDD / carrier ASR", failure: "Carrier returns 503 or no route",
    summary: "The carrier delivers inbound calls and accepts outbound calls across a provisioned Session Initiation Protocol (SIP) trunk.",
    lesson: "Phone-number routing, outbound call delivery, moving numbers between providers, permission to display caller ID, and trunk capacity are related but distinct carrier products. Production designs use explicit backup routes.",
    build: "Provision trunk IPs, authentication, number routes, call limits, codecs, and a secondary carrier path.",
    signal: "An inbound INVITE approaches your edge.", media: "Carrier offers media IP, port, and codecs in SDP.", state: "ingress_trunk = carrier_us_west_1",
    sources: ["rfc3261", "rfc3264"]
  },
  {
    id: "sip-gate", number: 4, name: "Call Setup Gate", kicker: "Session Initiation Protocol (SIP)", layer: "signal",
    terms: ["SIP", "INVITE", "ACK", "BYE", "REGISTER", "SIP responses", "IP", "SDP"],
    x: 0.2, z: 4.9, kind: "gate", metric: "Setup success / response code", failure: "4xx, 5xx, or timeout",
    summary: "Session Initiation Protocol (SIP) is the signaling conversation that creates, changes, and ends a call—not the voice itself.",
    lesson: "A common successful exchange is INVITE → 100 Trying → 180 Ringing → 200 OK → ACK, then BYE to hang up. Carrier trunks are often IP-authenticated and may not REGISTER like a desk phone.",
    build: "Capture one call with a SIP ladder and learn which system owns every response.",
    signal: "INVITE → 100 → 180 → 200 → ACK … BYE", media: "SDP is carried inside SIP messages.", state: "dialog_id + call legs are created",
    sources: ["rfc3261"]
  },
  {
    id: "sbc", number: 5, name: "Session Border Controller", kicker: "SBC: defend and normalize the edge", layer: "signal",
    terms: ["SBC", "PBX", "ACL", "NAT", "TLS", "RTP", "SRTP"],
    x: 3.2, z: 4.9, kind: "checkpoint", metric: "Rejected / rate-limited attempts", failure: "Fraud, malformed SIP, or topology leak",
    summary: "A Session Border Controller (SBC) is the guarded entrance between outside phone networks and your calling platform. It is more than a firewall and is not the business phone system itself.",
    lesson: "The edge can apply access-control lists (ACLs), authentication, rate limits, SIP normalization, topology hiding, network-address translation (NAT) handling, media anchoring, and fraud controls. Transport Layer Security (TLS) protects a signaling hop; it does not encrypt ordinary RTP audio.",
    build: "Allow only expected peers, normalize a narrow SIP profile, cap call rates, and log every rejection reason.",
    signal: "Validate peer, headers, rate, and dialog behavior.", media: "Optionally anchor media; require SRTP where supported.", state: "trusted_ingress + normalized tenant key",
    sources: ["rfc3261", "rfc3711"]
  },
  {
    id: "sdp", number: 6, name: "Media Agreement Lab", kicker: "Session Description Protocol (SDP)", layer: "signal",
    terms: ["SDP", "codec", "IP", "PCMU", "sendrecv"],
    x: 6.1, z: 4.9, kind: "lab", metric: "Negotiated codec", failure: "No common codec or bad IP/port",
    summary: "Session Description Protocol (SDP) is the note inside call setup that agrees where audio should go and which audio formats can be used.",
    lesson: "Each side advertises media capabilities. A compatible codec can pass without conversion; transcoding is needed only when policy or endpoints require it, consuming CPU and potentially quality.",
    build: "Start with a small codec policy, inspect the offer and answer, and prove both endpoints send to the negotiated addresses.",
    signal: "Offer in INVITE; answer in 200 OK.", media: "Codec + IP + port + direction are selected.", state: "codec = PCMU; direction = sendrecv",
    sources: ["rfc3264"]
  },
  {
    id: "media", number: 7, name: "Media Rail", kicker: "Move the actual audio", layer: "media",
    terms: ["RTP", "RTCP", "SRTP", "UDP", "RTT", "MOS", "NAT"],
    x: 8.4, z: 2.3, kind: "pipes", metric: "Loss / jitter / RTT / MOS estimate", failure: "One-way audio or choppy speech",
    summary: "Real-time Transport Protocol (RTP) packets carry audio separately from SIP; its companion RTCP reports timing and reception quality.",
    lesson: "Packet loss, jitter, latency, wrong NAT addresses, and blocked UDP create audible failures. RTP is not encrypted by default; SRTP adds confidentiality and integrity. MOS is an estimate, not a measured human opinion.",
    build: "Graph both media directions, negotiated endpoints, packet counts, loss, jitter, and RTT for a synthetic call.",
    signal: "SIP dialog can be healthy while audio is broken.", media: "RTP flows in both directions; RTCP reports quality.", state: "media_session is pinned to one node",
    sources: ["rfc3550", "rfc3711"]
  },
  {
    id: "freeswitch", number: 8, name: "Switchhouse", kicker: "Run the real-time call engine", layer: "media",
    terms: ["A-leg / B-leg", "CPU", "CRM", "UUID"],
    x: 8.4, z: -0.7, kind: "switchhouse", metric: "Sessions / channels / CPU", failure: "Media node crashes and live calls drop",
    summary: "FreeSWITCH runs real-time call legs, media, playback, recording, and bridges; it is not the whole SaaS.",
    lesson: "Think in endpoints, channels, calls, sessions, and bridges. One customer interaction can create an A-leg and several B-legs. Keep tenant auth, billing, CRM data, analytics, and workflow in surrounding services.",
    build: "Use narrow SIP profiles, a controlled event socket, versioned call-flow input, and disposable media nodes.",
    signal: "FreeSWITCH creates and controls multiple call legs.", media: "Playback, bridge, conference, and recording happen here.", state: "interaction_id links leg UUIDs",
    sources: ["fs-core", "fs-cdr"]
  },
  {
    id: "tenant-router", number: 9, name: "Tenant Router", kicker: "Load the right customer policy", layer: "control",
    terms: ["DID", "SIP"],
    x: 5.6, z: -0.7, kind: "router", metric: "Routing decision latency", failure: "Cross-tenant lookup or stale policy",
    summary: "The SaaS resolves one authoritative tenant identity, then loads one versioned call flow.",
    lesson: "Derive tenancy from a trusted ingress mapping such as carrier account + DID. Do not trust an arbitrary SIP header. Carry the tenant ID through every policy, event, recording, and data path.",
    build: "Compile a customer's visual flow into a versioned routing policy and atomically activate it.",
    signal: "A routing request returns the next application action.", media: "Media remains on the real-time node.", state: "tenant_17 / flow_v42 / interaction_9c2",
    sources: ["fs-core"]
  },
  {
    id: "ivr", number: 10, name: "Call Menu Workshop", kicker: "Interactive Voice Response (IVR)", layer: "control",
    terms: ["IVR", "DTMF", "RFC", "SIP", "RTP"],
    x: 2.7, z: -0.7, kind: "workshop", metric: "Containment / invalid input rate", failure: "Dead end, timeout, or retry loop",
    summary: "Interactive Voice Response (IVR) is the automated call menu that plays prompts and gathers keypad or spoken input.",
    lesson: "Dual-tone multi-frequency (DTMF) keypad input can travel as RFC 4733 telephone events, SIP INFO messages, or in-band audio—it is not always an audible tone. Speech recognition adds a separate service and failure surface.",
    build: "Create a short greeting, business-hours branch, two options, timeout behavior, operator escape, and fallback queue.",
    signal: "Application commands control prompt and digit collection.", media: "Prompts play; DTMF may use RTP events.", state: "intent = billing; attempts = 1",
    sources: ["rfc4733", "fs-core"]
  },
  {
    id: "queue", number: 11, name: "Queue Depot", kicker: "Match demand to available people", layer: "control",
    terms: ["FIFO", "SLA"],
    x: -0.2, z: -0.7, kind: "depot", metric: "Service level / abandon rate", failure: "Wait exceeds policy or no agents",
    summary: "A contact-center queue combines waiting callers, agent state, routing strategy, overflow, and abandonment policy.",
    lesson: "A simple FIFO is not full workforce routing. Production logic handles agent tiers, readiness, reservations, max wait, callbacks, voicemail, overflow, and priority without losing tenant isolation.",
    build: "Define queue goals, agent skills, overflow, max wait, callback policy, and the events needed to explain every decision.",
    signal: "The router requests an agent destination.", media: "Caller hears controlled hold media or announcements.", state: "position = 2; eligible_agents = 4",
    sources: ["fs-queues"]
  },
  {
    id: "agent", number: 12, name: "Agent Terminal", kicker: "Offer work to a human", layer: "media",
    terms: ["WebRTC", "HTTPS", "ICE", "STUN", "TURN", "DTLS-SRTP", "NAT"],
    x: -3.2, z: -0.7, kind: "terminal", metric: "Offer-to-answer / missed offers", failure: "Browser loses permission or connectivity",
    summary: "The agent lifecycle is presence → ready → reserved → offered → connected → wrap-up.",
    lesson: "A browser endpoint uses Web Real-Time Communication (WebRTC). Interactive Connectivity Establishment (ICE) tests possible audio paths. STUN helps discover a direct path; TURN relays media only when a direct path fails. WebRTC protects media with DTLS-SRTP. TURN is not an SBC.",
    build: "Create a browser softphone with explicit device checks, reconnect states, and a TURN path tested behind restrictive NAT.",
    signal: "Your app signaling coordinates an offer; SIP reaches the media edge.", media: "WebRTC uses DTLS-SRTP after ICE connectivity checks.", state: "agent_8 = connected; wrap_up = false",
    sources: ["webrtc", "rfc8445", "rfc8489", "rfc8656"]
  },
  {
    id: "bridge", number: 13, name: "Bridge Junction", kicker: "Join caller and agent legs", layer: "media",
    terms: ["SIP", "A-leg / B-leg"],
    x: -6.0, z: -0.7, kind: "junction", metric: "Answer / transfer success", failure: "Orphaned leg after transfer",
    summary: "The interaction joins separate call legs; transfers and conferences create still more legs and events.",
    lesson: "Blind transfer sends the caller onward immediately. Consultative transfer creates another leg so the agent can speak first. Hold, bridge, conference, and disposition are distinct state changes.",
    build: "Model the interaction above individual leg UUIDs so reporting survives transfers and retries.",
    signal: "New INVITEs and BYEs alter the leg graph.", media: "The media node bridges selected channels.", state: "interaction has caller + agent + consult legs",
    sources: ["fs-core", "fs-cdr"]
  },
  {
    id: "recording", number: 14, name: "Recording Vault", kicker: "Handle sensitive evidence", layer: "safety",
    terms: ["PCI DSS", "HIPAA"],
    x: -8.3, z: -3.2, kind: "vault", metric: "Pause / retention / access audit", failure: "Sensitive data enters a recording",
    summary: "Recording capability does not create legal permission; consent, retention, and access depend on context and jurisdiction.",
    lesson: "Choose start, stop, pause, channel layout, encryption, retention, deletion, and audited access deliberately. Keep payment data out of recordings, transcripts, and logs under Payment Card Industry Data Security Standard (PCI DSS) controls. Health Insurance Portability and Accountability Act (HIPAA) responsibility is not removed merely by encryption.",
    build: "Attach a jurisdiction-aware policy, visible agent state, payment pause flow, encryption keys, retention job, and access audit.",
    signal: "Application events control recording state.", media: "Authorized audio is written to protected storage.", state: "policy + consent + retention + audit trail",
    sources: ["pci", "hhs", "ftc"]
  },
  {
    id: "evidence", number: 15, name: "Evidence Office", kicker: "Turn events into product data", layer: "control",
    terms: ["CDR", "UUID"],
    x: -5.6, z: -3.2, kind: "office", metric: "Event lag / duplicate rate", failure: "Leg CDR counted as a customer interaction",
    summary: "Normalize immutable real-time events into interactions, call legs, reports, and a usage ledger.",
    lesson: "FreeSWITCH can emit one Call Detail Record (CDR) per call leg, so CDR count is not customer-call count. An idempotent event pipeline should reconstruct transfers and retries without making node-local state the product source of truth.",
    build: "Store raw events, normalize idempotently, link legs to one interaction, and calculate billable usage from explicit rules.",
    signal: "Lifecycle events arrive asynchronously.", media: "Recording metadata references protected media objects.", state: "events → legs → interaction → usage ledger",
    sources: ["fs-cdr"]
  },
  {
    id: "compliance", number: 16, name: "Launch Gate", kicker: "Prove the market-specific duties", layer: "safety",
    terms: ["STIR/SHAKEN", "TCPA", "TSR", "PCI DSS", "HIPAA"],
    x: -2.8, z: -3.2, kind: "hall", metric: "Unmet launch controls", failure: "Normal route used for emergency calling",
    summary: "Emergency calling, caller identity, outbound consent, payments, and health data require separate launch gates.",
    lesson: "In the US, design dedicated 911 location, routing, callback, direct dialing, and notification behavior. STIR/SHAKEN is a provider-signed caller-ID attestation framework, not proof of the human caller. The Telephone Consumer Protection Act (TCPA), Telemarketing Sales Rule (TSR), PCI DSS, HIPAA, and recording-law scopes differ.",
    build: "Define supported markets and use cases; obtain specialist review and carrier capabilities before enabling each regulated path.",
    signal: "Emergency and identity metadata follow dedicated policies.", media: "Sensitive audio can change storage and routing requirements.", state: "launch gates are evidence-backed, not one checkbox",
    sources: ["fcc911", "fccstir", "ftc", "pci", "hhs"]
  },
  {
    id: "ops", number: 17, name: "Operations Tower", kicker: "Observe an actual call, end to end", layer: "safety",
    terms: ["HTTP", "PDD", "ASR", "SLA", "RTP", "RTT", "MOS"],
    x: 0.2, z: -3.2, kind: "tower", metric: "Synthetic-call success", failure: "Green process health but broken audio",
    summary: "A successful website-style HTTP response and a running process do not prove that a caller and agent can hear each other.",
    lesson: "Measure setup success, response codes, post-dial delay (PDD), answer rate, queue service-level targets (SLA), abandonment, both RTP directions, loss, jitter, round-trip time (RTT), estimated Mean Opinion Score (MOS), and carrier/node/tenant breakdowns. Synthetic calls provide end-to-end evidence.",
    build: "Run scheduled calls through real carrier and agent paths, assert audio both ways, and retain SIP, media, and event correlation IDs.",
    signal: "Trace dialog timing and response ownership.", media: "Verify packets and recognizable audio in both directions.", state: "one correlation ID spans carrier → media → product data",
    sources: ["rfc3550", "rfc3261"]
  },
  {
    id: "scale", number: 18, name: "Scale Control", kicker: "Grow without pretending calls are stateless", layer: "safety",
    terms: ["SIP", "RTP"],
    x: 3.2, z: -3.2, kind: "control", metric: "Capacity / regional failover", failure: "Overload or media-node loss",
    summary: "New calls can load-balance across nodes, but an active call remains pinned to its real-time node.",
    lesson: "Unlike stateless web traffic, live media has node-local timing and channel state. Admit calls within tested capacity, drain nodes before deploys, use regional and carrier redundancy, and expect a crashed media node to drop its live calls.",
    build: "Load-test call setup and media separately, cap admission, route new sessions away from degraded nodes, and practice region/carrier failure.",
    signal: "Route new dialogs based on health and capacity.", media: "Do not promise seamless mid-call failover without a proven architecture.", state: "active calls pinned; new calls reroutable",
    sources: ["fs-core", "rfc3550"]
  }
];

export const ROUTES = {
  inbound: {
    label: "Inbound support call",
    description: "A customer dials support, chooses Billing, waits briefly, and reaches a browser agent.",
    stations: STATIONS.map((station) => station.id),
  },
  media: {
    label: "No-audio investigation",
    description: "Follow setup into SDP and RTP, where a healthy SIP dialog can still hide one-way audio.",
    stations: ["carrier", "sip-gate", "sbc", "sdp", "media", "freeswitch", "agent", "ops"],
  },
  scale: {
    label: "Launch readiness",
    description: "Trace the product and operational controls needed before customer traffic is safe to scale.",
    stations: ["number-yard", "tenant-router", "queue", "recording", "evidence", "compliance", "ops", "scale"],
  }
};

export const MISCONCEPTIONS = [
  ["SIP carries the voice", "SIP controls the session; RTP/SRTP carries media."],
  ["A DID is a phone line", "A DID is a routing address; inventory and capacity are separate."],
  ["FreeSWITCH is the SaaS", "It is the real-time engine inside a larger tenant control plane."],
  ["One call means one CDR", "Transfers and retries create multiple legs and usually multiple CDRs."],
  ["TLS encrypts the call", "SIP TLS protects a signaling hop; media needs SRTP."],
  ["STUN relays media", "STUN discovers candidates; TURN is the relay when direct ICE paths fail."],
  ["A green server means calls work", "Only an end-to-end synthetic call can prove signaling and two-way audio."],
];
